let express = require("express")
const { adduser, login, resetpwd } = require("../controlers/usercont")
const { upload, add, getprod, upddct, deldct, updprod, updpimg, addrv } = require("../controlers/prodcont")
const { addcart, incqty, decqty, delcart, getcart } = require("../controlers/cartcon")
const { addCategory, addSubcategory, getCategories } = require("../controlers/categorycon")
let route = new express.Router()
route.post("/adduser", adduser)
route.post("/login", login)
route.post("/addprod", upload.single("pimg"), add)
route.get("/getprod", getprod)
route.put("/upddct", upddct)
route.put("/deldct", deldct)
route.put("/updprod", updprod)
route.put("/updimg", upload.single("pimg"), updpimg)
route.post("/addcart", addcart)
route.put("/inc", incqty)
route.put("/dec", decqty)
route.delete("/delcart/:id", delcart)
route.get("/getcart/:uid", getcart)
route.put("/addrv", addrv)
route.post("/restpwd", resetpwd)
route.post("/addcategory", addCategory)
route.post("/addsubcat", addSubcategory)
route.get("/categories", getCategories)

module.exports = route